export interface overtimeData {
    user_id: number,
    type: number,
    start_date: Date,
    end_date: Date,
    start_time: string,
    end_time: string,
    actual_check_in: string,
    actual_check_out: string,
    break_hours: number,
    no_of_hours: number,
    purpose: string,
    primary_status: number,
    backup_status: number,
    primary_approver: number,
    backup_approver: number,
    approver_note: string,
    _token: string,
}