export interface shiftsData {
    user_id: number,
    type: number,
    new_shift_type: number,
    date: Date,
    check_in: string,
    check_out: string,
    actual_check_in: string,
    actual_check_out: string,
    between_start: string,
    between_end: string,
    primary_status: number,
    backup_status: number,
    shift_length: number,
    paid_hours: number,
    primary_approver: number,
    backup_approver: number,
    approver_note: string,
    onsite: boolean,
    _token: string,
    approved_by: number,
    approved_at: Date,
}